libeos-payg/manager.c
Rather than setting a single long timeout period and then expiring when
that is reached, poll every 60s to see if the expiry time has been
reached. This avoids the timeout going out of sync with the wall clock
when resuming from suspend, and also works around issues with the system
clock and timezone changing.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
https://phabricator.endlessm.com/T22074
=> libeos-payg: Poll for the expiry time to avoid issues with suspend

debian/not-installed
https://phabricator.endlessm.com/T22281
=> debian: fix build on ARM

libeos-payg/boottime-source.c, libeos-payg/boottime-source.h, libeos-payg/clock.c, libeos-payg/clock.h, libeos-payg/fake-clock.c, libeos-payg/fake-clock.h, libeos-payg/manager-service.c, libeos-payg/manager.c, libeos-payg/manager.h, libeos-payg/meson.build, libeos-payg/provider.c, libeos-payg/provider.h, libeos-payg/real-clock.c, libeos-payg/real-clock.h, libeos-payg/service.c, libeos-payg/tests/boottime-source.c, libeos-payg/tests/manager.c, libeos-payg/tests/meson.build, libeos-payg/tests/plugins/test-provider.c, meson.build
https://phabricator.endlessm.com/T24300
=> T24300 Use CLOCK_BOOTTIME during runtime

.gitignore, debian/rules, debian/tests/control, debian/tests/gnome-desktop-testing-root, eos-payg-csv/tests/meson.build, eos-payg-generate/tests/meson.build, eos-paygd/tests/meson.build, libeos-payg-codes/tests/meson.build, libeos-payg/clock-jump-source.c, libeos-payg/clock-jump-source.h, libeos-payg/manager.c, libeos-payg/meson.build, libeos-payg/provider.c, libeos-payg/provider.h, libeos-payg/service.c, libeos-payg/tests/clock-jump-source.c, libeos-payg/tests/meson.build, meson.build, meson_options.txt
https://phabricator.endlessm.com/T24501
=> T24501 Detect clock jumps

eos-paygd/main.c
https://phabricator.endlessm.com/T27051
=> Make eos-paygd use the watchdog timer

libeos-payg/fake-clock.c
We have a 64 bit integer in one struct definition, and we're casting
another struct that contains nothing that large to it. The struct
that only contains smaller types only has a 32-bit alignment
constraint, but is being cast to something with a 64-bit alignment
constraint, so gcc complains.
Break the 64-bit item into high/low components and recombine/break
apart as required.
=> fix build on arm

eos-paygd/main.c
If the current boot occurred with Secure Boot disabled, it doesn't make
sense to enforce PAYG because (a) it's easily circumventable by
replacing the initramfs and (b) Secure Boot has likely been disabled
because the machine is in one of two states:
1. It has been fully paid off and unlocked (though note that it's also
possible to have Secure Boot enabled on an unlocked machine, in which
case EOSPAYG_active will not be set).
2. It is being debugged by a developer who has used PKpriv to disable
Secure Boot.
This commit also adds a command line flag --skip-sb-check, so a
developer can have eos-paygd in enforcing mode even with Secure Boot
off (though adding the flag would require editing the initramfs or using
a specially created debug image).
https://phabricator.endlessm.com/T27735
=> eos-paygd: Don't enforce PAYG if Secure Boot is off

eos-paygd/main.c
If the EFI variable EOSPAYG_active is unset, don't enforce PAYG. This
means the only step necessary to unlock a PAYG machine (either because
it has been paid off or is being debugged) is to unset this EFI
variable.[1] The LSM ensures that only eos-paygd can write to this
variable on PAYG computers.[2]
[1] https://phabricator.endlessm.com/T27981
[2] https://phabricator.endlessm.com/T27046
https://phabricator.endlessm.com/T28053
=> eos-paygd: Don't enforce PAYG if EOSPAYG_active is unset

eos-paygd/main.c
https://phabricator.endlessm.com/T27050
=> Activate the LSM before root pivot

eos-paygd/main.c, libeos-payg/manager-interface.h, libeos-payg/manager-service.c, libeos-payg/meson.build, libeos-payg/provider.c, libeos-payg/util.c, libeos-payg/util.h
https://phabricator.endlessm.com/T27133
=> Shut down after 10 minutes when there's no credit remaining

eos-paygd/main.c
https://phabricator.endlessm.com/T28417
=> Properly retry connecting to D-Bus

eos-paygd/main.c, libeos-payg/manager-service.c, libeos-payg/util.c
https://phabricator.endlessm.com/T27133
=> Properly shut down with no credit remaining

meson.build
This reverts commit 9bb77c6bc7d910aa428c689ac6fb07a627fd67c6.
https://phabricator.endlessm.com/T27693
=> Revert "meson.build: Add -Wno-error=deprecated-declarations"

libeos-payg/util.c
Instead of a sync and a hard shutdown, we'll try telling systemd to shut
down cleanly. If that fails, or fails to happen in a reasonable amount
of time, a hard shutdown will follow.
https://phabricator.endlessm.com/T31166
=> libeos-payg: Try a clean shutdown first

eos-paygd/main.c, libeos-payg/hwclock.c, libeos-payg/service.c
https://phabricator.endlessm.com/T32734
=> paygd / hwclock: Log when not enforcing or when clock jumps are detected

libeos-payg/service.h
Increase the security level after the latest fixes.
https://phabricator.endlessm.com/T33082
=> paygd: Increase security level

libeos-payg/manager-service.c
https://phabricator.endlessm.com/T32734
=> paygd: Log code entering attemps and results

eos-paygd/main.c
Based on review comments in https://github.com/endlessm/eos-payg/pull/104.
I have not tested this at all (even to compile it).
=> Various small logging cleanups

libeos-payg/manager.c
https://phabricator.endlessm.com/T34550
=> manager: Fix credit consumption on clock jumps

README.md, debian/control, eos-payg-generate/meson.build, eos-paygd/main.c, eos-paygd/meson.build, libeos-payg-codes/meson.build, libeos-payg-codes/tests/meson.build, libeos-payg/meson.build, libeos-payg/tests/meson.build, libeos-payg/tests/plugins/meson.build, meson.build
Spotted while working on https://github.com/endlessm/eos-meta/pull/783 and checking the details of the daemon's logging. Not strictly related but let's attach it to that ticket anyway:
https://phabricator.endlessm.com/T33896
=> Require glib 2.74

eos-paygd/main.c, libeos-payg/util.c
https://phabricator.endlessm.com/T35468
=> Slightly improve logging when a shutdown is scheduled or triggered
