endlessm/eos-payg

- libeos-payg/manager.c
As wjt has pointed out https://www.evanjones.ca/linear-search.html, we
can use the plots there to argue that linear search is fine for lists up
to 256 elements; it’s the fastest search up to around 100 elements, and
competitive for array sizes a bit larger than that.
Also, this isn’t performance critical, and hasn’t been found to be slow
in practice, so the FIXME seems unwarranted in several respects.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
> libeos-payg: Drop a FIXME comment

- debian/eos-paygd.postinst
The sysusers configuration is installed at
/usr/lib/sysusers.d/eos-paygd.conf, but systemd-sysusers was being
called with the path in /lib. This works in the ostree builder where
/lib is a symlink to /usr/lib, but not in OBS where that's not the case.
https://phabricator.endlessm.com/T23969
> debian: Call systemd-sysusers on correct path in paygd postinst

- eos-paygd/eos-payg.conf
- meson.build
A few bits of mutually-unrelated followup:
* My intention on https://github.com/endlessm/eos-payg/pull/24 was that creating the key file should be all that's needed to enable Endless PAYG on a system, but I didn't actually implement that change.
* On a related pull request I learned that cc.get_supported_arguments() exists.
https://phabricator.endlessm.com/T23606
> Improve compiler flag detection; set Enabled=true by default

- .flake8
- eos-payg-ctl/eos-payg-ctl
`-a` and `--bus-address` matches the short and long names used by the daemon (courtesy of libgsystemservice), and is useful when running a development copy of the daemon on the session bus.
https://github.com/ambv/black is a reasonable (and reasonably popular) auto-formatter for Python code. In a few places, it disagrees with flake8's defaults; tweak flake8 to ignore these.
Perhaps in a future life I'll make flake8- and black-cleanliness a compile-time check.
Preliminary work for https://phabricator.endlessm.com/T23781
> eos-payg-ctl: add --bus-address argument; tweak code style

- debian/eos-payg-data.install
- eos-payg-ctl/eos-payg-ctl
- eos-payg-ctl/get-clock-boottime.c
- eos-payg-ctl/meson.build
Now that the "ExpiryTime" and "RateLimitEndTime" properties of
EpgProvider are in terms of CLOCK_BOOTTIME instead of being UNIX
timestamps, modify eos-payg-ctl to interpret them correctly. For now
this is implemented using a helper program until we get Python 3.7 on
the stable branch, which will give us time.CLOCK_BOOTTIME (to be used
with time.clock_gettime()).
https://phabricator.endlessm.com/T24300
> eos-payg-ctl: Understand CLOCK_BOOTTIME properties

- eos-payg-ctl/eos-payg-ctl
Some stylistic stuff, and one very minor improvement to use the same offset for the two properties, rather than introducing fractional differences. All absolutely inessential.
https://phabricator.endlessm.com/T24300
> eos-payg-ctl: improve conversion from BOOTTIME to human-readable timestamp

- libeos-payg/manager.c
When the EpgManager is migrating the state files, and specifically
deleting the "expiry-time" file so the "clock-time" and "expiry-seconds"
files can be used instead, there was a logical error in the callback for
the file deletion, file_load_delete_cb(). After calling
epg_multi_task_return_boolean() on the success code path, it also called
epg_multi_task_return_error() resulting in assertion failures:
Jan 14 12:23:47 endless eos-paygd1[728]: g_error_copy: assertion 'error
!= NULL' failed
Jan 14 12:23:47 endless eos-paygd1[728]: epg_multi_task_return_error:
assertion 'error != NULL' failed
This also seems to have the effect of locking the computer (putting it
back in the state where a payg code is required to use it). So fix the
logic so that already provisioned computers that upgrade to …
> manager: Fix logic for migrating state files

- libeos-payg/manager.c
- libeos-payg/tests/manager.c
We want the EpgManager to save state to the disk upon startup, because
otherwise an unclean shutdown would leave us in the wrong state upon the
next boot. However the call to epg_manager_save_state_async() is in
file_load_cb() in an if block that only gets executed if the two state
files used to store the expiry time have been loaded, which means it
doesn't get executed if we're migrating from the old single state file
(migrating from expiry-time to clock-time and expiry-seconds).
So move the save_state_async() call to set_expiry_time() so that it
happens every time the expiry time is updated. This applies in the
migration case above but also a few other code paths, such as when
there's an error loading the state data. This commit also removes the
save_state_async() call in add_code(), …
> manager: Save state after migrating state files

- debian/control
- debian/eos-payg-generate-tests.install
- debian/eos-payg-generate.install
- debian/rules
- debian/tests/gnome-desktop-testing
- eos-payg-csv/tests/meson.build
Currently, the OBS builds are broken (though Jenkins builds are not)
because OBS performs the installed tests and does not see the required
data files.
This ensures the test files are available in that case.
https://phabricator.endlessm.com/T25205
> eos-payg-csv: ensure test files available for OBS

- eos-paygd/eos-paygd.service.in
An out-of-tree provider needs to be able to enumerate the contents of
/dev; PrivateDevices=yes causes a minimal /dev to be mounted for the
executed process, which means the important devices are not visible to
eos-paygd.
PrivateDevices=true implies a number of other restrictions:
* @raw-io system calls are blocked
* CAP_MKNOD and CAP_SYS_RAWIO are removed from CapabilityBoundingSet
* DevicePolicy=closed is set
The first two restrictions are already by other lines in this file; add
DevicePolicy=closed. (The out-of-tree provider opens the relevant device
using UDisks, essentially circumventing this restriction, but in a
controlled way.)
https://phabricator.endlessm.com/T24134
> .service: remove PrivateDevices, add DevicePolicy

- debian/control
- eos-payg-ctl/eos-payg-ctl
This adds a dependency on Python 3.7. (Actually, it's possible that this
was added in Python 3.6, but that version was never in Endless OS.)
Please do not merge this until PAYG development on the eos3.5 branch has wound down.
https://phabricator.endlessm.com/T25065
> eos-payg-ctl: use time.CLOCK_BOOTTIME directly

- libeos-payg/service.c
I tried to use g_clear_object() on a GSource pointer, but those are not
objects. Use g_source_destroy() followed by g_source_unref() instead to
avoid a seg fault on shutdown.
https://phabricator.endlessm.com/T24501
> service: Fix a seg fault on shutdown

- libeos-payg/manager-interface.h
- libeos-payg/manager-service.c
- libeos-payg/manager.c
- libeos-payg/provider.c
- libeos-payg/provider.h
- libeos-payg/tests/manager.c
- libeos-payg/tests/plugins/test-provider.c
Return the amount of time added into the add_code function
of the daemon.
https://phabricator.endlessm.com/T24128
> eos-payg: Return the amount of time added

- libeos-payg/manager-interface.h
- libeos-payg/manager-service.c
- libeos-payg/manager.c
- libeos-payg/provider.c
- libeos-payg/provider.h
- libeos-payg/tests/manager.c
- libeos-payg/tests/plugins/test-provider.c
Add a property that returns the prefix and sufix of the codes used,
making the interface of code insertion for user-friendly.
https://phabricator.endlessm.com/T25987
> eos-payg: Add a prefix and suffix property of the codes

- debian/control
- eos-paygd/main.c
- libeos-payg/meson.build
- libeos-payg/service.c
- libeos-payg/service.h
Currently in epg_service_secure_init_sync() we have "g_assert (provider
!= NULL)" which means that eos-paygd hits an assertion failure in case
it's running on a non-PAYG system, or in case it's running on a PAYG
system using the filesystem to store state. In the latter case the
provider is only found to be enabled after the root pivot, and the
secure init happens before the root pivot.
This commit removes the assertion, and instead checks if no providers
have been found after the root pivot. If none were found and the
EOSPAYG_active EFI variable is set, we error out and force a poweroff
after 10 minutes. Otherwise the user could disable PAYG by zeroing out
the state data. The EFI variable check ensures that this security
measure only applies to Phase 4 systems, which will set …
> Error out if PAYG is not enabled when it should be

- libeos-payg/service.c
Before commit 97d4edf36, the provider field of an EpgService object was
always non-NULL after epg_service_startup_async() completed, since an
EpgManager was used as a fallback if other providers weren't enabled,
regardless of whether or not Endless PAYG was enabled. But after commit
97d4edf36, we may complete startup with no provider if none were
enabled. So add a check to epg_service_shutdown() so we don't try to use
a NULL provider object, which I believe is causing a seg fault.
Since provider_notify_enabled_cb() is already called by
epg_service_startup_complete() and there we exit the service if the
provider is disabled, we could remove the epg_provider_get_enabled()
check in manager_new_cb() and avoid the need for this patch. But perhaps
leaving in the early enabled check is better, …
> service: Don't seg fault on shutdown w/ no provider

- libeos-payg/service.c
Fix a g_debug() message which has a %s but no argument provided for it,
which causes a seg fault when a payg image is booted with no providers
enabled.
It's frightening that any crashing bug in eos-paygd brings the whole
system down. I filed this ticket about doing an audit:
https://phabricator.endlessm.com/T27681
https://phabricator.endlessm.com/T27581
> service: Fix a g_debug missing format parameters

- eos-paygd/main.c
There's no reason for this variable to be visible outside this file.
https://phabricator.endlessm.com/T27051
> eos-paygd: Make watchdog_fd static

- eos-paygd/main.c
Once eos-paygd opens /dev/watchdog, we have to keep pinging it as long
as the system is running to prevent a forced poweroff by the kernel.
Currently EpgService exits with no error set in case no provider is
enabled and the EFI variable EOSPAYG_active is not set (meaning either
the system is not Phase 4 PAYG, or it has been paid off, or it has not
been provisioned yet). So in that case, continue to iterate the main
loop forever so we keep pinging the watchdog. The topic of having
eos-paygd exit when the computer is shutting down is covered by
https://phabricator.endlessm.com/T27718
Since the provisioning process currently requires a reboot, there's no
danger that eos-paygd will remain in this ping-only state on a PAYG
enabled machine.
https://phabricator.endlessm.com/T27051
> eos-paygd: Don't exit after opening the watchdog

- meson.build
Increase the warning level to 3. Meson decides which -W cflags that
translates to. And set werror to true, which translates to -Werror.
The impetus for this is that any bugs in eos-paygd have potentially
severe impact (e.g. not enforce PAYG or crash and temporarily brick a
computer).
> meson.build: Change warning_level to 3 and werror to true

- eos-paygd/eos-paygd-2.service.in
- eos-paygd/main.c
We need to chroot into /sysroot before the root pivot occurs so
the dbus socket (among many other things) is visible to us. But
we have to do that *after* telling system it's ok to proceed with
the pivot, and start deleting the root of our current directory
hierarchy.
Do this with a special sd_notify variant that lets us chroot
away from the space the sd notification socket lives in before
sending the notification.
Also, to make this chroot possible, relax a bunch of sandboxing
settings.
https://phabricator.endlessm.com/T27037
> eos-paygd: chroot before the root pivot

- eos-paygd/main.c
- eos-paygd/meson.build
- libeos-payg/service.c
- libeos-payg/service.h
Use an EFI variable to ensure we can't go back to an older
system with known PAYG bugs.
https://phabricator.endlessm.com/T27685
> eos-paygd: Add support for EOSPAYG_securitylevel

- eos-paygd/main.c
Currently we ping the watchdog timer every 10 seconds, but this is a bit
excessive given that it's a 20 minute timer. So increase the time
between pings to 60 seconds, and update the documentation to match the
changes made here[1]. I'm not sure exactly what the performance cost is
of this ping, which should just be in memory. We do know the timer stops
when the computer is suspended, so it's okay that pings won't happen
in that state.
[1] https://github.com/endlessm/linux/pull/502
> eos-paygd: Only ping watchdog every minute

- eos-payg-csv/tests/meson.build
- eos-payg-generate/tests/meson.build
- meson.build
I spotted these while doing a round of translations on https://phabricator.endlessm.com/T27764.
TODO:
```
manual-provision-payg/meson.build:1: WARNING: Custom target input 'testsuite' can't be converted to File object(s).
This will become a hard error in the future.
```
but I don't plan to work further on this branch.
> WIP: fix Meson warnings

- eos-paygd/main.c
- libeos-payg/service.c
- libeos-payg/service.h
- libeos-payg/util.c
- libeos-payg/util.h
This EFI variable should prove useful when debugging PAYG systems which
in production are so locked down as to be difficult to debug. You can,
for example, set a bit to tell eos-paygd not to use the LSM, which means
the process will show up in /proc and can be attached to with gdb. This
variable cannot easily be set on a production system because the LSM
ensures that only eos-paygd can access EFI variables which have the
prefix "EOSPAYG". The expected flow is that the developer will build a
bootable EFI blob which unlocks the computer in question if the account
number on the computer matches the one compiled into the blob. See
https://phabricator.endlessm.com/T28290. Then, even if the primary OS
isn't booting, you could disable Secure Boot, boot from a USB drive, and
set EOSPAYG_debug …
> Implement support for EOSPAYG_debug EFI variable

- libeos-payg/provider.c
- libeos-payg/service.c
Currently if one enters a final unlock code which pays off a computer's
loan, the EpgProvider object sets `enabled` to FALSE and sets the expiry
time far into the future, so that PAYG is no longer enforced. However,
since the EOSPAYG_active EFI variable is left set on Phase 4+ systems,
upon the next boot, eos-paygd will initiate a shutdown since it doesn't
expect state data to be in a "PAYG disabled" state while EOSPAYG_active
is set. Thus the user can't really use their paid off computer for more
than a few minutes at a time.
So this commit adds an `unlocked` signal to EpgProvider, which will be
emitted by the Angaza backend when the final unlock code has been
entered. The signal emission is caught by eos-paygd which deletes
EOSPAYG_active, so the computer will be free to use on the next …
> Add and use EpgProvider::unlocked signal

- libeos-payg/errors.h
- libeos-payg/manager-interface.h
- libeos-payg/manager-service.c
- libeos-payg/manager.c
- libeos-payg/provider.c
- libeos-payg/provider.h
- libeos-payg/tests/manager.c
- libeos-payg/tests/plugins/test-provider.c
Add an account-id property to be shown on the user's unlock
screen every time he adds a Pay-As-You-Go credit. As of now, we
don't assign a proper code to the user, so this is mostly a
foundation for the eos-payg-nonfree module.
https://phabricator.endlessm.com/T28491
> eos-payg: Add the account-id property

- eos-paygd/main.c
- libeos-payg/util.c
- libeos-payg/util.h
We need a way for plugins to check if they should use modern or legacy
code paths. This will allow us to, for example, disable datastore
encryption on phase 2 deployments.
https://phabricator.endlessm.com/T27052
> Add util function for checking if this is a legacy or modern PAYG system

- debian/control
This is needed for building libgsystemservice. We may also want to use
it in the future to compile the gtk-doc comments we have in the source
into HTML.
https://phabricator.endlessm.com/T29330
> debian/control: Add gtk-doc-tools dep

- eos-paygd/main.c
- libeos-payg/hwclock.c
- libeos-payg/meson.build
- libeos-payg/service.c
- libeos-payg/service.h
- libeos-payg/util.h
In certain circumstances the RTC and the system clock can be out of sync
with eachother. This causes problems for accurate time keeping over a
reboot.
Make eos-paygd keep the two in sync.
https://phabricator.endlessm.com/T30571
> eos-paygd: Add RTC updating

- eos-paygd/eos-paygd-2.service.in
We've been trying to start eos-paygd very early in the boot, but
this appears to set up a race condition that leaves some systems
in a state where eos-paygd can't connect to dbus.
Instead, let's sneak eos-paygd after fs mounting and before the
root pivot.
https://phabricator.endlessm.com/T30797
> eos-paygd: Start after fs mounting but before root pivot

- debian/control
- eos-paygd/main.c
- eos-paygd/meson.build
- libeos-payg/efi.c
- libeos-payg/efi.h
- libeos-payg/meson.build
- libeos-payg/service.c
- libeos-payg/util.c
- libeos-payg/util.h
Due to the unique nature of our efi variable access patterns, libefivar
isn't currently suited to our needs.
For now, replace efivar with our own tiny library to deal with efivarfs.
This also allows us to simplify API to fit our requirements, and make it
more resilient to things we consider bugs in eos-paygd.
There are future plans (T30696, T30698) to reintroduce the libefivar
dependency when we have time to address our needs in upstream friendly
ways.
https://phabricator.endlessm.com/T25224
> efi: Add mini efi library to replace efivar

- libeos-payg/service.c
We shouldn't be checking for the presence of EFI variables
when running eos-paygd after the root pivot. This happens in
legacy deployments that never used EFI variables at all.
Non-PAYG systems also launch the daemon in this way, and some
such systems won't have EFI support at all.
https://phabricator.endlessm.com/T30914
> service: Don't do efi variable lookups inappropriately

- libeos-payg/service.h
Enough has changed this release that we've decided to bump the
security level.
https://phabricator.endlessm.com/T30900
> eos-paygd: Increase security level

- libeos-payg/efi.c
- libeos-payg/efi.h
This variable is non-standard and weird, but in the cases it
exists it might be useful to query.
https://phabricator.endlessm.com/T31137
> efi: Add a function to check for SecureBootOption

- eos-paygd/eos-paygd.service.in
Killmode=None is deprecated, and will eventually stop working. Also, its
use is only currently important for eos-paygd when run from the initramfs,
so we can simply drop it from the legacy service (that launches it from
the rootfs)
https://phabricator.endlessm.com/T31590
> eos-paygd: Stop using deprecated Killmode for legacy eos-paygd

- eos-paygd/eos-paygd-2.service.in
We use KillMode=None so systemd doesn't try to kill our process, but this
has been deprecated because it prevents systemd from trying to kill
processes.
Instead, we switch to IgnoreOnIsolate=true, which tells systemd not to
(try to) shut down the process when performing isolation, such as at
root pivot and shutdown.
We already renamed out process to avoid the systemd root-pivot killing
spree, however that alone doesn't prevent systemd from trying to manage
service life-cycle.
Our process remains unkillable, and systemd will shut the computer down
immediately if a user tries to stop the service.
https://phabricator.endlessm.com/T31590
> eos-paygd: Stop using deprecated KillMode=None

- README.md
We've recently discussed the possibility of system shutdown interrupting
a write to non volatile storage. The conclusion is that eos-paygd is
safe against these interruptions, so we don't have to deal with
shutting the daemon down cleanly and all that entails.
However, the reason it's safe is because all currently in use nv storage
backends can handle interrupted writes safely (this does not include the
file backend, which is not used in the real world).
Make a note of this in the README so future developers realize both that
shutdown is safe, and that atomicity is a critical design criteria for
the storage backends to maintain this safety.
https://phabricator.endlessm.com/T27718
> readme: Make a note regarding shutdown during nv write

- libeos-payg/hwclock.c
This will aid in diagnosing when the RTC hardware is busted the daemon
enforces the PAYG lock and forces a shutdown. We have seen this failing
on some ECS EF20EA machines in the field, but without having access to
the machines we can't determine why it fails. We suspect a hardware
failure, but having the actual error printed on the logs will be help.
https://phabricator.endlessm.com/T32703
> hwclock: Print the for failing to opening the RTC

- libeos-payg/hwclock.c
Since when payg is enforced we disable the kernel SYSTOHC functionality
and prevent any other userspace process from accessing the RTC,
eos-paygd effectively becomes responsive for keeping the RTC up-to-date.
This code previously assumed the RTC was configured to use the local
time, which is not actually the case -- the RTC will always use UTC on
standalone Endless OS installations.
This commit changes eos-paygd behavior to always store the UTC time in
the RTC, and treat values read from the RTC as UTC time.
https://phabricator.endlessm.com/T32733
> hwclock: Keep the RTC in UTC

- eos-paygd/main.c
- libeos-payg/manager-service.c
- libeos-payg/util.c
- libeos-payg/util.h
If the daemon receives one of these termination signals we should
trigger a poweroff, so the computer does not continue to run without
paygd.
This is required for us to allow the daemon to be terminated by systemd
during shutdown but not manually by the user.
https://phabricator.endlessm.com/T33088
https://phabricator.endlessm.com/T32815
> paygd: Request a poweroff on SIGTERM / SIGINT

- eos-paygd/main.c
Handle all cases where the service object exits with an error by
requesting a poweroff after 20 minutes. The causes we expect to trigger
this logic are the provider data being errased or damaged, or paygd
losing the bus name (which can happen if the D-Bus server gets
terminated or restarted).
https://phabricator.endlessm.com/T33037
> paygd: Request poweroff if the service exits with any error

- libeos-payg/manager-interface.h
- libeos-payg/manager-service.c
- libeos-payg/manager.c
- libeos-payg/provider.c
- libeos-payg/provider.h
- libeos-payg/tests/manager.c
- libeos-payg/tests/plugins/test-provider.c
- meson.build
Create a new CodeUIString read-only D-Bus property that will be used by
providers to inform the UI on how their unlock codes should be referred
to.
This also overrides its value in EpgManager with 8.
https://phabricator.endlessm.com/T33325
> Create CodeLength D-Bus property

- debian/eos-paygd.install
- eos-paygd/eos-paygd.tmpfile
- eos-paygd/main.c
- eos-paygd/meson.build
- meson_options.txt
In systems with fragile storage (ex., SSD or eMMC) the journal is only
kept in RAM as does not persist over reboot. In such systems we still
want logs from eos-paygd to persist, without having to write all system
logs to persistent storage.
The solution for that is to create a separate log file for eos-paygd, in
addition to forwarding logs to the journal.
https://phabricator.endlessm.com/T33220
> paygd: Write logs to a separate file

- libeos-payg/manager.c
- libeos-payg/provider.c
- libeos-payg/provider.h
- libeos-payg/service.c
When a clock jump is detected, we already need to get the current wallclock time to calculate the jump size. Let's pass this information to the provider, so it can better decide how to handle the jump.
Also update the "manager" provider to use the time passed by caller in its wallclock_time_changed implementation instead of calculating again.
https://phabricator.endlessm.com/T33873
> service: Pass current time to provider on clock jumps

- libeos-payg/provider.c
This parameter was added a few commits ago, but the documentation was missed.
> provider: Document now_sec on epg_provider_shutdown_finish

- dracut/meson.build
- eos-payg-csv/tests/meson.build
- eos-payg-csv/tests/taptestrunner.py
- eos-payg-generate/tests/meson.build
- eos-payg-generate/tests/taptestrunner.py
- eos-paygd/meson.build
- libeos-payg-codes/tests/meson.build
- libeos-payg/tests/meson.build
- meson.build
This was a bug in the copy-pasted TAP test runner, which I have fixed upstream & applied here.
https://phabricator.endlessm.com/T34768
> Fix NUL bytes in Python test output

- libeos-payg-codes/tests/meson.build
- libeos-payg/tests/meson.build
This reverts the hunks of 15f0d9319f29c56cdd345b67892013786084921b
which affect the tests written in C, as opposed to the Python ones.
In my environment, this only showed a warning like:
Unknown TAP version. The first line MUST be `TAP version <int>`. Assuming version 12.
but for JP there are many other errors:
8/11 eos-payg:eos-payg / manager                      SKIP            0.11s
Unknown TAP version. The first line MUST be `TAP version <int>`. Assuming version 12.
stdout:  1: UNKNOWN: /manager/load-empty: OK
[...]
ERROR: Unknown TAP output lines for a supported TAP version.
This is probably a bug in the test; if they are not TAP syntax, prefix them with a #
This is not essential. Revert.
https://phabricator.endlessm.com/T34768
> Partially revert "tests: Tell Meson our tests emit TAP output"

- eos-payg-generate/main.c
- libeos-payg-codes/codes.c
- libeos-payg-codes/codes.h
- libeos-payg-codes/tests/codes.c
- libeos-payg/manager.c
Paying on the same calendar day each month is predictable and standard
for other subscription models. But previously, doing this would either
mean issuing two codes in months with 31 days (one for 30 days, another
for 1 day) or the user running out of credit for a day.
By supporting 31-day codes, it is possible to either issue a 30-day or
31-day code depending on the month, or (more likely) to simply issue a
31-day code every month, leaving the user with 7-8 days' extra credit at
the end of each year.
(We could in principle add 28-day and 29-day codes to support February
and lunar calendars "natively", but there are only 5 more bits available
in this bitfield.)
https://phabricator.endlessm.com/T33556
> Support 31-day codes

- libeos-payg/manager.c
- libeos-payg/tests/manager.c
Due to a software bug, some systems ended up with aproximately 50 years of credit. To recover from this situation, this commit adjusts systems with more than 5 years of credit to have 31 days of credit. These values were chosen because we do not expect a system to have 5+ years of credit by valid means, and because 31 days is the standard payment period with deployments using the manager (aka phase1) provider.
https://phabricator.endlessm.com/T34550
> manager: Adjust credit on systems with way too much

- debian/control
- meson_options.txt
As described in the commit message, this is needed because two paths are looked up from `systemd.pc`. Evidently the `systemd` package is installed in the Jenkins build environment because 8f0ba1bf2427e4329369e60eefa54ce9773a35a2 builds fine on Jenkins; and evidently it is present in the OBS build environment on 5.1 because that same change built fine on `eos:5.1:endless`; but the build failed on `eos:master:endless`.
https://phabricator.endlessm.com/T35174
> Build-depend on systemd

- debian/control
- eos-paygd/eos-paygd.tmpfile
In commit acc43e1ed67e9a8ab8b56eef0b6084108e6e8c89, JP wrote:
> This will instruct systemd to remove any files that have not been
> created, modified or accessed in the last 90 days. Ideally we would have
> used 'm:90d' so just opening a file for reading would not interfere with
> its cleanup, but this is only supported on systemd 249+ and EOS 4.0.x
> ships systemd 247.
Endless OS 6 ships systemd 254, so we can now implement the TODO.
https://phabricator.endlessm.com/T35528
> payg: Ignore access time when cleaning log files

- .gitmodules
- libeos-payg/efi.c
- libeos-payg/meson.build
- meson.build
[libglnx](https://gitlab.gnome.org/GNOME/libglnx) is a helper library designed to be embedded into another project as a git submodule. Among other things, it provides an attribute you can attach to a variable holding a file descriptor, which calls `close()` on it when it goes out of scope if it is non-negative. Any error from `close()` is ignored, just like our existing code, except if it is `EBADF`, which indicates a programming error.
Add a libglnx submodule, and use `glnx_autofd` throughout our EFI code. Most cases are simple but `eospayg_efi_init()` is a little bit more involved.
This will make it easier to propagate errors to the caller in a future commit.
Additionally, fix a couple of errors in docstrings.
https://phabricator.endlessm.com/T35459
> efi: Simplify closing fds

- debian/libeos-payg-1-dev.install
- debian/rules
- libeos-payg/meson.build
To build eos-payg-nonfree against libeos-payg static lib for avoiding API/ABI issue, build and install libeos-payg as both shared & static libs.
https://phabricator.endlessm.com/T35437
> libeos-payg: Build libeos-payg as both shared & static libs

- debian/control
Since commit 35b3213, the generated eos-payg-1.pc file has listed
libsystemd as a private dependency, I think because libeos-payg-1
internally links to libsystemd and so any binary that statically links
libeos-payg-1 now links to libsystemd.
```diff
-Requires: gio-2.0, glib-2.0, gobject-2.0
+Requires: gio-2.0 >=  2.44, glib-2.0 >=  2.44, gobject-2.0 >=  2.44
+Requires.private: libsystemd, gio-unix-2.0, libpeas-1.0
```
Add libsystemd-dev as a dependency of the libeos-payg-1-dev package so
that applications which declare the latter as a build dependency can
still build.
https://phabricator.endlessm.com/T35437
> Add libsystemd-dev dep to -dev package

- debian/control
- libeos-payg-codes/tests/meson.build
- libeos-payg/tests/meson.build
- meson.build
This reverts commit 2f1171b16ecd5e9d4e042e8faac1eae452a6340c, which reverted part of commit 15f0d9319f29c56cdd345b67892013786084921b.
We now have a newer GLib which emits the "TAP version XX" header, so let's try again to tell Meson that the C tests emit TAP output, and bump the GLib dependency to the version that added that header.
> Re-enable TAP parsing for C tests

- eos-paygd/main.c
- libeos-payg/efi.c
- libeos-payg/efi.h
- libeos-payg/service.c
- libeos-payg/util.c
Previously, many functions to read and manipulate EFI variables would return FALSE or NULL on error, but there was no reliable way to determine the cause of the error. Some error paths would set `errno`, but not all.
Add a `GError **` parameter to these functions, and set it whenever FALSE or NULL is returned.
In addition, extend `eospayg_efi_var_read()` to check whether the variable contents match the caller's expected size, which almost all callers would previously do. This way we only need to write the logic to set the GError in this case once, here, and the callers' error handling is simplified.
I did not add GError ** parameters to the various miscellaneous accessors.
This PR requires the out-of-tree plugins to be updated in lockstep because I chose not to preserve the API & ABI. …
> Report GError when EFI functions fail

- libeos-payg/efi.c
- libeos-payg/efi.h
Introduce eospayg_efi_setupmode() to check the system boots with SetupMode, or not. It check the EFI variable:
SetupMode-8be4df61-93ca-11d2-aa0d-00e098032b8c for normal cases.
https://phabricator.endlessm.com/T34898
> efi: Introduce eospayg_efi_setupmode()
